### ISSUE TITLE
Request: Add support for a fixed attribution window

### ISSUE THREAD

**Issue by benjaminsavage** [patcg-individual-drafts/ipa#16]
The current "IPA end-to-end" document does not provide a way to constrain the attributed conversions based on the amount of time between the source and trigger event. 

Currently, if any of the source-events in an IPA query share a common match key (and "attribution constraint ID") with any of the trigger-events that came after it, they'll be attributed. 

Today, it is common for advertisers to count the number of "1-day / 7-day / 28-day conversions".  If this is behaviour that advertisers would like to keep (as opposed to just, "Do any of the trigger events I've included in this query come from the same match-key and later in time than any of these source events I've included in this query") then we would need to add support for this.

It would be great to get feedback about how much demand there is for this use-case, and to provide a sample oblivious algorithm to achieve this outcome.

**Comment by csharrison** [comment]
I think these kinds of lookback / conversion windows are a really important use-case we should try to address. We implemented them in ARA via an [expiration](https://wicg.github.io/attribution-reporting-api/#attribution-source-expiry) parameter on source events.

I wanted to mention that at least in the Google Ads stack, the conversion window is [configured](https://support.google.com/google-ads/answer/3123169) per conversion type, and can vary based on the interaction type (view, click).

**Comment by benjaminsavage** [comment]
We now have code in the IPA codebase which implements exactly this.
