### ISSUE TITLE
IPA Biweekly Meeting Agenda Request - Interfaces for setMatchKey and getEncryptedMatchKey

### ISSUE THREAD

**Issue by eriktaubeneck** [patcg-individual-drafts/ipa#54]
## Agenda+: setMatchKey and getEncryptedMatchKey

As we begin to prototype these APIs, we need to align on a common interface for both functions. The goal of this discussion is to get feedback on the current design outlined in #52.

## Time

15-30 minutes.

## Issue Link

#52

**Comment by richajaindce** [comment]
@csharrison would be great if you could join the meeting and we could discuss the interface for setMatchKey and getEncryptedMatchKey in detail.

**Comment by csharrison** [comment]
Yes I can join!
